spring.application.name=api
#configura a porta da aplicação
server.port=8888

#desabilita(por enquanto) o acesso a banco de dados
spring.autoconfigure.exclude=org.springframework.boot.jdbc.autoconfigure.DataSourceAutoConfiguration
spring.datasource.url=jdbc:postgres://8520193157fbf379cdc75eb83d786f0a9cf667b35c6e97eb5c6e9e894ce71136:sk_z8uWl6z5hDrE0cvfA7Wqm@pooled.db.prisma.io:5432/postgres?sslmode=require
